FROM jupyter/datascience-notebook:python-3.10

RUN pip install shioaji==0.0.0
WORKDIR /home/work
RUN wget https://raw.githubusercontent.com/Sinotrade/Sinotrade.github.io/master/tutorial/shioaji_tutorial.ipynb
EXPOSE 8888

ENTRYPOINT [ "jupyter", "lab", "--allow-root", "--ip=0.0.0.0"]